#' Contract walks to cluster nodes
#'
#' \code{contract_walks} returns a walks with vericies contracted to cluster nodes from an object generated by \code{random_walk}.
#'
#' @param walks output of \code{random_walk}.
#' @param cluster vector of cluster assignement of the original pointcloud.
#'
#' @return \code{contract_wlaks} returns a list of vertex indices and indices of walks starts.
#'
#' @export
contract_walks <- function(walks, clusters) {
  contracted <- list()
  for (i in 1:length(walks$starts)) {
    w <- select_paths_points(walks, i)

    edges <- lapply(1:(length(w) - 1), function(j, k = j + 1) clusters[w[j:k]]) # walk as list of edges (using cluster numbering)
    edges <- edges[lapply(edges, function(j) j[1] != j[2]) %>% unlist] # remove edges leading to self

    w <- c(
      edges[[1]][1],
      unlist(lapply(edges, function(i) i[2]))
    )
    contracted[[i]] <- w
  }

  starts <- c(1, unlist(lapply(contracted, length)))
  starts <- starts[-length(starts)]
  starts <- sapply(1:length(starts), function(i) sum(starts[1:i]))

  list(v = unlist(contracted), starts = starts)
}

contract_walks1 <- function(walks, clusters,verbose=TRUE) {
  contracted <- list()
  walks$v<-clusters[walks$v]
  return(remove_cycles(walks,verbose=verbose))
}
