smooth_path <- function(
  d,
  n = NULL
) {
  fit <- apply(d, 2, spline) %>% lapply(., function(i) i$y) %>% do.call(cbind, .) # fit curve
  if (is.null(n)) return(fit)
  apply(fit, 2, function(i) approx(i, n=n)$y) # interpolation
}

#' Generate consensus path
#'
#' \code{consensus_path} takes a set of pathways (generated from simulations of random walks through a graph) and creates a consensus path which represents
#'  their topology. Length of the consensus path is 3 times the max walk length. Missing points are interpolated.
#' @param pathways a pathways list object, as generated by \code{create_pathways_object}.
#' @param class a single pathway class number by which to filter pathways.
#' @param coordinates coordinate matrix, preferrably of non-reduced dimensionality, to use for averaging pathways.
#'
#' @return \code{consensus_path} returns a coordinate matrix containing vertices of consensus path.
#'
#' @export
consensus_path <- function(
  pathways,
  class,
  coordinates
) {
  i <- which(lapply(pathways$classes, function(i) (class %in% i)) == TRUE)
  if (length(i) < 1) {
    warning("Invalid class")
    return("fail")
  }
  inds <- pathways$walks[i]
  vertices <- lapply(inds, function(i) coordinates[i, ])
  len <- max(unlist(lapply(inds, length))) * 3
  smooth_paths <- lapply(vertices, function(i) smooth_path(i, n = len))
  d <- ncol(smooth_paths[[1]])
  concat <- do.call(cbind, smooth_paths)
  nDimMean <- function(vec, d, n) sapply(1:d, function(i) mean(vec[seq(1, n, by=d)+(i-1)]))
  n <- ncol(concat)
  consensus <- t(apply(concat, 1, function(i) nDimMean(i, d, n)))
  consensus
}

#' Create a pathways list object
#'
#' \code{create_pathways_object} takes a \code{walks} list object, as generated by \code{random_walk_N} or related function, and
#'  generates a pathways list object, containing a \code{walks} slot with distinct walks (index vectors) and a \code{classes} slot
#'  with class numbers per walk.
#' @param walks a \code{walks} list object, as generated by \code{random_walk_N} or related function.
#' @param classes a vector of class numbers corresponding to walks.
#'
#' @return \code{create_pathways_object} returns a list with slots \code{walks} and \code{classes}.
#'
#' @export
create_pathways_object <- function(
  walks,
  classes
) {
  pathways <- list()
  pathways$classes <- as.list(classes)
  pathways$walks <- lapply(1:length(pathways$classes), function(i) { select_paths_points(walks, walks.selection[i]) })
}
