# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

computeGCD <- function(a, b) {
    .Call('_tviblindi_computeGCD', PACKAGE = 'tviblindi', a, b)
}

computeLCM <- function(a, b) {
    .Call('_tviblindi_computeLCM', PACKAGE = 'tviblindi', a, b)
}

bicgSparse <- function(A, b, nb_iter = 100L, err = 10^-6) {
    .Call('_tviblindi_bicgSparse', PACKAGE = 'tviblindi', A, b, nb_iter, err)
}

build_boundary_C <- function(filtration, sort_input = TRUE) {
    .Call('_tviblindi_build_boundary_C', PACKAGE = 'tviblindi', filtration, sort_input)
}

cgSparse <- function(A, b, iguess, nb_iter = 100L, err = 10^-6) {
    .Call('_tviblindi_cgSparse', PACKAGE = 'tviblindi', A, b, iguess, nb_iter, err)
}

connect_cliques <- function(cliques) {
    .Call('_tviblindi_connect_cliques', PACKAGE = 'tviblindi', cliques)
}

createKNNgraph_cos <- function(X, D, K, N) {
    .Call('_tviblindi_createKNNgraph_cos', PACKAGE = 'tviblindi', X, D, K, N)
}

createKNNgraph_eu <- function(X, D, K, N) {
    .Call('_tviblindi_createKNNgraph_eu', PACKAGE = 'tviblindi', X, D, K, N)
}

boundaries <- function(f, sort_input = TRUE) {
    .Call('_tviblindi_boundaries', PACKAGE = 'tviblindi', f, sort_input)
}

faces <- function(f, sort_input = TRUE) {
    .Call('_tviblindi_faces', PACKAGE = 'tviblindi', f, sort_input)
}

rips_complex_filtration_values <- function(f, coord, threshold) {
    .Call('_tviblindi_rips_complex_filtration_values', PACKAGE = 'tviblindi', f, coord, threshold)
}

alpha_complex_filtration_values_C <- function(f, coord, f_u) {
    .Call('_tviblindi_alpha_complex_filtration_values_C', PACKAGE = 'tviblindi', f, coord, f_u)
}

firstleft <- function(A, start, nb_iter = 100L, eps = 1e-6) {
    .Call('_tviblindi_firstleft', PACKAGE = 'tviblindi', A, start, nb_iter, eps)
}

get_rep_C <- function(cycle, boundary) {
    .Call('_tviblindi_get_rep_C', PACKAGE = 'tviblindi', cycle, boundary)
}

get_rep_lazy <- function(cycle, R, B, update = FALSE) {
    .Call('_tviblindi_get_rep_lazy', PACKAGE = 'tviblindi', cycle, R, B, update)
}

get_rep_lazy_2 <- function(cycle, R, B, update = FALSE) {
    .Call('_tviblindi_get_rep_lazy_2', PACKAGE = 'tviblindi', cycle, R, B, update)
}

get_cycle_representation <- function(cycle, reduced_boundary_matrix, nonreduced_boundaries = 0L, update_rb = FALSE) {
    .Call('_tviblindi_get_cycle_representation', PACKAGE = 'tviblindi', cycle, reduced_boundary_matrix, nonreduced_boundaries, update_rb)
}

get_rep_straight <- function(cycle, R, B, update = FALSE) {
    .Call('_tviblindi_get_rep_straight', PACKAGE = 'tviblindi', cycle, R, B, update)
}

get_rep_straight_modified <- function(cycle, R, update = FALSE) {
    .Call('_tviblindi_get_rep_straight_modified', PACKAGE = 'tviblindi', cycle, R, update)
}

get_reps_straight_modified <- function(cycles, R, update = FALSE) {
    .Call('_tviblindi_get_reps_straight_modified', PACKAGE = 'tviblindi', cycles, R, update)
}

interpolate_trajectories <- function(pts, coef = 200) {
    .Call('_tviblindi_interpolate_trajectories', PACKAGE = 'tviblindi', pts, coef)
}

jaccard_coeff_parallel <- function(idx) {
    .Call('_tviblindi_jaccard_coeff_parallel', PACKAGE = 'tviblindi', idx)
}

jaccard_coeff <- function(idx) {
    .Call('_tviblindi_jaccard_coeff', PACKAGE = 'tviblindi', idx)
}

jaccard_coeff_true_parallel <- function(idx) {
    .Call('_tviblindi_jaccard_coeff_true_parallel', PACKAGE = 'tviblindi', idx)
}

knn_annoy <- function(mat, K = 100L, trees = 150L) {
    .Call('_tviblindi_knn_annoy', PACKAGE = 'tviblindi', mat, K, trees)
}

openmp_knn_C <- function(coordinates, K, distance_function = 0L) {
    .Call('_tviblindi_openmp_knn_C', PACKAGE = 'tviblindi', coordinates, K, distance_function)
}

hello <- function() {
    .Call('_tviblindi_hello', PACKAGE = 'tviblindi')
}

phatBoundary <- function(filtration, maxdimension) {
    .Call('_tviblindi_phatBoundary', PACKAGE = 'tviblindi', filtration, maxdimension)
}

C_random_walk_adj <- function(A, start, nb_iter = 100L) {
    .Call('_tviblindi_C_random_walk_adj', PACKAGE = 'tviblindi', A, start, nb_iter)
}

C_random_walk_adj_N <- function(A, start, nb_iter = 100L, N = 1L) {
    .Call('_tviblindi_C_random_walk_adj_N', PACKAGE = 'tviblindi', A, start, nb_iter, N)
}

C_random_walk_adj_N_push <- function(A, start, N = 1L) {
    .Call('_tviblindi_C_random_walk_adj_N_push', PACKAGE = 'tviblindi', A, start, N)
}

C_random_walk_adj_N_push_std <- function(A, start, N = 1L) {
    .Call('_tviblindi_C_random_walk_adj_N_push_std', PACKAGE = 'tviblindi', A, start, N)
}

C_random_walk <- function(sim, start, N = 1L) {
    .Call('_tviblindi_C_random_walk', PACKAGE = 'tviblindi', sim, start, N)
}

C_random_walk_adj_stf_N <- function(A, start, beta, gamma, ptime, nb_iter = 100L, N = 1L) {
    .Call('_tviblindi_C_random_walk_adj_stf_N', PACKAGE = 'tviblindi', A, start, beta, gamma, ptime, nb_iter, N)
}

C_random_walk_adj_u <- function(A, start, nb_iter = 100L) {
    .Call('_tviblindi_C_random_walk_adj_u', PACKAGE = 'tviblindi', A, start, nb_iter)
}

relative_filtration <- function(indices, filtration, sort_output) {
    .Call('_tviblindi_relative_filtration', PACKAGE = 'tviblindi', indices, filtration, sort_output)
}

remove_back <- function(triplet, time) {
    .Call('_tviblindi_remove_back', PACKAGE = 'tviblindi', triplet, time)
}

remove_cycles_int_list <- function(series_list, series_list_unique) {
    .Call('_tviblindi_remove_cycles_int_list', PACKAGE = 'tviblindi', series_list, series_list_unique)
}

rips_from_spadj <- function(As, nbVertices, threshold, maxdimension = 1L) {
    .Call('_tviblindi_rips_from_spadj', PACKAGE = 'tviblindi', As, nbVertices, threshold, maxdimension)
}

C_sigma <- function(D, target, nIter = 64L, tol = 1e-5) {
    .Call('_tviblindi_C_sigma', PACKAGE = 'tviblindi', D, target, nIter, tol)
}

unique_simplex_inds <- function(cmplx, sort_input) {
    .Call('_tviblindi_unique_simplex_inds', PACKAGE = 'tviblindi', cmplx, sort_input)
}

reindex_cmplx <- function(cmplx, inds) {
    .Call('_tviblindi_reindex_cmplx', PACKAGE = 'tviblindi', cmplx, inds)
}

lowerbound_rb <- function(reduced_boundary_matrix, threshold) {
    .Call('_tviblindi_lowerbound_rb', PACKAGE = 'tviblindi', reduced_boundary_matrix, threshold)
}

path_1simplex_indices <- function(walks, cmplx) {
    .Call('_tviblindi_path_1simplex_indices', PACKAGE = 'tviblindi', walks, cmplx)
}

witness_from_points <- function(landmarksin, ws, alpha2, maxdimension = 1L) {
    .Call('_tviblindi_witness_from_points', PACKAGE = 'tviblindi', landmarksin, ws, alpha2, maxdimension)
}

witness_from_distances <- function(IND, DIST, alpha2, maxdimension = 1L) {
    .Call('_tviblindi_witness_from_distances', PACKAGE = 'tviblindi', IND, DIST, alpha2, maxdimension)
}

strong_witness_from_distances <- function(IND, DIST, alpha2, maxdimension = 1L) {
    .Call('_tviblindi_strong_witness_from_distances', PACKAGE = 'tviblindi', IND, DIST, alpha2, maxdimension)
}

witness_from_distances_cliques <- function(IND, DIST, alpha2, maxdimension = 1L) {
    .Call('_tviblindi_witness_from_distances_cliques', PACKAGE = 'tviblindi', IND, DIST, alpha2, maxdimension)
}

strong_witness_from_distances_cliques <- function(IND, DIST, alpha2, maxdimension = 1L) {
    .Call('_tviblindi_strong_witness_from_distances_cliques', PACKAGE = 'tviblindi', IND, DIST, alpha2, maxdimension)
}

internal_sample_points <- function(ws, nbL = 100L) {
    .Call('_tviblindi_internal_sample_points', PACKAGE = 'tviblindi', ws, nbL)
}

