# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

denoise_matrix <- function(coords, kNN_idcs, K, n_iter) {
    .Call('_tviblindi_denoise_matrix', PACKAGE = 'tviblindi', coords, kNN_idcs, K, n_iter)
}

knn_annoy <- function(mat, K = 100L, trees = 150L) {
    .Call('_tviblindi_knn_annoy', PACKAGE = 'tviblindi', mat, K, trees)
}

kNN_exact <- function(coordinates, K, distance_function = 0L) {
    .Call('_tviblindi_kNN_exact', PACKAGE = 'tviblindi', coordinates, K, distance_function)
}

solve_conjugate_gradient <- function(A, b, iguess, nb_iter = 100L, err = 10e-6) {
    .Call('_tviblindi_solve_conjugate_gradient', PACKAGE = 'tviblindi', A, b, iguess, nb_iter, err)
}

build_boundary_matrix <- function(filtration, sort_input = TRUE) {
    .Call('_tviblindi_build_boundary_matrix', PACKAGE = 'tviblindi', filtration, sort_input)
}

phat_boundary <- function(filtration, maxdimension) {
    .Call('_tviblindi_phat_boundary', PACKAGE = 'tviblindi', filtration, maxdimension)
}

C_sigma <- function(D, target, nIter = 64L, tol = 1e-5) {
    .Call('_tviblindi_C_sigma', PACKAGE = 'tviblindi', D, target, nIter, tol)
}

unique_simplex_idcs <- function(cmplx, sort_input) {
    .Call('_tviblindi_unique_simplex_idcs', PACKAGE = 'tviblindi', cmplx, sort_input)
}

witness_from_points <- function(landmarksin, ws, alpha2, maxdimension = 1L) {
    .Call('_tviblindi_witness_from_points', PACKAGE = 'tviblindi', landmarksin, ws, alpha2, maxdimension)
}

witness_from_distances <- function(IND, DIST, alpha2, maxdimension = 1L) {
    .Call('_tviblindi_witness_from_distances', PACKAGE = 'tviblindi', IND, DIST, alpha2, maxdimension)
}

strong_witness_from_distances <- function(IND, DIST, alpha2, maxdimension = 1L) {
    .Call('_tviblindi_strong_witness_from_distances', PACKAGE = 'tviblindi', IND, DIST, alpha2, maxdimension)
}

witness_from_distances_cliques <- function(IND, DIST, alpha2, maxdimension = 1L) {
    .Call('_tviblindi_witness_from_distances_cliques', PACKAGE = 'tviblindi', IND, DIST, alpha2, maxdimension)
}

strong_witness_from_distances_cliques <- function(IND, DIST, alpha2, maxdimension = 1L) {
    .Call('_tviblindi_strong_witness_from_distances_cliques', PACKAGE = 'tviblindi', IND, DIST, alpha2, maxdimension)
}

internal_sample_points <- function(ws, nbL = 100L) {
    .Call('_tviblindi_internal_sample_points', PACKAGE = 'tviblindi', ws, nbL)
}

boundaries <- function(f, sort_input = TRUE) {
    .Call('_tviblindi_boundaries', PACKAGE = 'tviblindi', f, sort_input)
}

faces <- function(f, sort_input = TRUE) {
    .Call('_tviblindi_faces', PACKAGE = 'tviblindi', f, sort_input)
}

alpha_complex_filtration_values_C <- function(f, coord, f_u) {
    .Call('_tviblindi_alpha_complex_filtration_values_C', PACKAGE = 'tviblindi', f, coord, f_u)
}

walk_1simplex_indices <- function(walks, cmplx) {
    .Call('_tviblindi_walk_1simplex_indices', PACKAGE = 'tviblindi', walks, cmplx)
}

random_walks_from_adj <- function(A, start, N = 1L) {
    .Call('_tviblindi_random_walks_from_adj', PACKAGE = 'tviblindi', A, start, N)
}

C_random_walk_adj <- function(A, start, nb_iter = 100L) {
    .Call('_tviblindi_C_random_walk_adj', PACKAGE = 'tviblindi', A, start, nb_iter)
}

C_random_walk_adj_N <- function(A, start, nb_iter = 100L, N = 1L) {
    .Call('_tviblindi_C_random_walk_adj_N', PACKAGE = 'tviblindi', A, start, nb_iter, N)
}

C_random_walk_adj_N_push <- function(A, start, N = 1L) {
    .Call('_tviblindi_C_random_walk_adj_N_push', PACKAGE = 'tviblindi', A, start, N)
}

remove_cycles_int_list <- function(series_list, series_list_unique) {
    .Call('_tviblindi_remove_cycles_int_list', PACKAGE = 'tviblindi', series_list, series_list_unique)
}

get_rep_straight <- function(cycle, R, B, update = FALSE) {
    .Call('_tviblindi_get_rep_straight', PACKAGE = 'tviblindi', cycle, R, B, update)
}

get_rep_straight_modified <- function(cycle, R, update = FALSE) {
    .Call('_tviblindi_get_rep_straight_modified', PACKAGE = 'tviblindi', cycle, R, update)
}

get_reps_straight_modified <- function(cycles, R, update = FALSE) {
    .Call('_tviblindi_get_reps_straight_modified', PACKAGE = 'tviblindi', cycles, R, update)
}

interpolate_trajectories <- function(pts, coef = 200) {
    .Call('_tviblindi_interpolate_trajectories', PACKAGE = 'tviblindi', pts, coef)
}

