#' Remove cycles from paths
#'
#' \code{remove_cycles} takes a \code{walks} object (simulations of random walks through a graph) and removes any
#'  cycles occuring within the walks.
#' @param walks a \code{walks} object, as generated by \code{random_walk_N} or related function.
#' @param verbose Boolean; if true, report which trajectories contained cycles.
#'
#' @return \code{remove_cycles} returns a modified \code{walks} object.
#'
#' @export
remove_cycles <- function(walks, verbose = TRUE) {
  ends <- c(walks$starts[-1]-1, length(walks$v))
  walks.list <- lapply(1:length(walks$starts), function(i, v = walks$v, starts = walks$starts) {
    v[starts[i]:ends[i]]
  })
  w <- remove_cycles_int_list(walks.list, lapply(walks.list, unique), TRUE)
  
  starts <- c(1, unlist(lapply(w, length)))
  starts <- starts[-length(starts)]
  starts <- sapply(1:length(starts), function(i) sum(starts[1:i]))
  
  list(v = unlist(w), starts = starts)
}
