#' Remove cycles from paths
#'
#' \code{remove_cycles} takes a \code{walks} object (simulations of random walks through a graph) and removes any
#'  cycles occuring within the walks.
#' @param walks a \code{walks} object, as generated by \code{random_walk_N} or related function.
#' @param verbose Boolean; if true, report how many trajectories contained cycles.
#' @param detailed Boolean; if true and if verbose is true, report which trajectories contained cycles.
#'
#' @return \code{remove_cycles} returns a modified \code{walks} object.
#'
#' @export
remove_cycles <- function(walks, verbose = TRUE, detailed = FALSE) {
  ends <- c(walks$starts[-1]-1, length(walks$v))
  walks.list <- lapply(1:length(walks$starts), function(i, v = walks$v, starts = walks$starts) {
    v[starts[i]:ends[i]]
  })
  
  lengths1 <- NULL
  if (verbose) {
    lengths1 <- unlist(lapply(walks.list, length))
  }
  
  w <- remove_cycles_int_list(walks.list, lapply(walks.list, unique))
  
  lengths2 <- NULL
  if (verbose) {
    lengths2 <- unlist(lapply(w, length))
    ineq <- which(lengths1 != lengths2)
    if (detailed && length(ineq > 0)) {
      cat("Cycles in", paste0(ineq, collapse = ", "), "\n")
    }
    cat("In total,", length(ineq), "out of", length(lengths2), "series cyclical.\n")
  }
  
  starts <- c(1, unlist(lapply(w, length)))
  starts <- starts[-length(starts)]
  starts <- sapply(1:length(starts), function(i) sum(starts[1:i]))
  
  list(v = unlist(w), starts = starts)
}
