#' Launch graphical user interface for tviblindi trajectories analysis
#' 
#' @param input_fcs_path Path to analysed FCS file.
#' @param origin Index in *coords* of first point in all trajectories.
#' @param pseudotime Pseudotime object, as generated by *assign_distance*.
#' @param coords Full expression matrix.
#' @param coords_clusters Clustered expression matrix.
#' @param clusters Cluster assignments (per event).
#' @param filtration Filtration on all points in *coords*.
#' @param layout 2D projection matrix.
#' @param walks_raw Walks object as output of function *randow_walk_...*.
#' @param b Boundary matrix of *filtration*.
#' @param rb Reduced boundary matrix of *filtration*.
#' @example #launch_shiny("data/input.FCS", readRDS("data/origin.RDS"), readRDS("data/pseudotime.RDS"), readRDS("data/coords.RDS"), readRDS("data/coords_clusters.RDS"), readRDS("data/clusters.RDS"), readRDS("data/filtration.RDS"), readRDS("data/layout.RDS"), readRDS("data/walks_raw.RDS"), readRDS("data/b.RDS"), readRDS("data/rb.RDS"), 1:1000)
launch_shiny <- function(input_fcs_path,
                         origin,
                         pseudotime,
                         coords,
                         coords_clusters,
                         clusters,
                         filtration,
                         layout,
                         walks_raw,
                         b,
                         rb,
                         event_sel = NULL) {
  
  server_env <- environment(shiny_server)
  
  server_env$input_fcs_path  <- input_fcs_path;  cat("Loaded input FCS file path\n")
  server_env$origin          <- origin;          cat("Loaded origin\n")
  server_env$pseudotime      <- pseudotime;      cat("Loaded pseudotime\n")
  server_env$coords          <- coords;          cat("Loaded coords\n")
  server_env$coords_clusters <- coords_clusters; cat("Loaded clustered coordinates\n")
  server_env$clusters        <- clusters;        cat("Loaded clusters\n")
  server_env$filtration      <- filtration;      cat("Loaded filtration\n")
  server_env$layout          <- layout;          cat("Loaded 2D layout\n")
  server_env$walks_raw       <- walks_raw;       cat("Loaded random walks\n")
  server_env$b               <- b;               cat("Loaded boundary matrix\n")
  server_env$rb              <- rb;              cat("Loaded reduced boundary matrix\n")
  server_env$event_sel       <- event_sel;       cat("Loaded events selection\n")
  
  app <- shiny::shinyApp(shiny_ui, shiny_server)
  shiny::runApp(app)
}
