#' Launch graphical user interface for tviblindi trajectories analysis
#' 
#' @param input_fcs_path Path to analysed FCS file.
#' @param origin Index in *coords* of first point in all trajectories.
#' @param pseudotime Pseudotime object, as generated by *assign_distance*.
#' @param coords Full expression matrix.
#' @param coords_clusters Clustered expression matrix.
#' @param clusters Cluster assignments (per event).
#' @param filtration Filtration on all points in *coords*.
#' @param layout 2D projection matrix.
#' @param walks_raw Walks object as output of function *randow_walk_...*.
#' @param b Boundary matrix of *filtration*.
#' @param rb Reduced boundary matrix of *filtration*.
#' @example #launch_shiny("data/input.FCS", readRDS("data/origin.RDS"), readRDS("data/pseudotime.RDS"), readRDS("data/coords.RDS"), readRDS("data/coords_clusters.RDS"), readRDS("data/clusters.RDS"), readRDS("data/filtration.RDS"), readRDS("data/layout.RDS"), readRDS("data/walks_raw.RDS"), readRDS("data/b.RDS"), readRDS("data/rb.RDS"), 1:1000)
launch_shiny <- function(input_fcs_path,
                         origin,
                         pseudotime,
                         coords,
                         coords_clusters,
                         clusters,
                         filtration,
                         layout,
                         walks_raw,
                         b,
                         rb,
                         event_sel = NULL) {
  
  shiny_inputs_dir <- "tviblindi_tmp"
  if (dir.exists(shiny_inputs_dir)) {
    message("Shiny inputs folder exists. Proceed?")
    readline()
  }
  
  dir.create(shiny_inputs_dir)
  message("Exporting objects for Shiny")
  message("-> path to analysed FCS file")
  saveRDS(input_fcs_path, file.path(shiny_inputs_dir, "input_fcs_path.RDS"))
  message("-> cell of origin index")
  saveRDS(origin, file.path(shiny_inputs_dir, "origin.RDS"))
  message("-> pseudotime values")
  saveRDS(pseudotime, file.path(shiny_inputs_dir, "pseudotime.RDS"))
  message("-> expression matrix")
  saveRDS(coords, file.path(shiny_inputs_dir, "coords.RDS"))
  message("-> clustered expression matrix")
  saveRDS(coords_clusters, file.path(shiny_inputs_dir, "coords_clusters.RDS"))
  message("-> cluster definitions")
  saveRDS(clusters, file.path(shiny_inputs_dir, "clusters.RDS"))
  message("-> filtration")
  saveRDS(filtration, file.path(shiny_inputs_dir, "filtration.RDS"))
  message("-> 2-dimensional layout")
  saveRDS(layout, file.path(shiny_inputs_dir, "layout.RDS"))
  message("-> simulated random walks")
  saveRDS(walks_raw, file.path(shiny_inputs_dir, "walks_raw.RDS"))
  message("-> boundary matrix")
  saveRDS(b, file.path(shiny_inputs_dir, "b.RDS"))
  message("-> reduced boundary matrix")
  saveRDS(rb, file.path(shiny_inputs_dir, "rb.RDS"))
  message("-> indices of events selected for analysis")
  saveRDS(event_sel, file.path(shiny_inputs_dir, "event_sel.RDS"))
  
  app <- shiny::shinyApp(shiny_ui, shiny_server)
  shiny::runApp(app)
}
